import json, os, re, zipfile, shutil
root='/mnt/data/workv7'
# Canonical data grounded in the supplied presentation; no unsupported ecological claims.
objects=[
{
'id':'dub-velikan','name':'Ботанический памятник природы «Бобруйский дуб-великан»','category':'botanical','categoryName':'Ботанический памятник природы местного значения','coords':[53.142472,29.229936],'coordsAccuracy':'verified',
'images':['images/dub.jpg','images/dub2.jpg','images/dub3.jpg'],'shortDesc':'Дуб-великан на перекрёстке улиц Гоголя и Чонгарской — старожил Бобруйска возрастом более трёхсот лет.','fullDesc':'📍 МЕСТОНАХОЖДЕНИЕ:\nг. Бобруйск, перекрёсток улиц Гоголя и Чонгарской, у Бобруйской крепости.\n\n📌 СТАТУС И ИСТОРИЯ:\nВ 2003 году Бобруйский городской исполнительный комитет объявил дерево ботаническим памятником природы местного значения «Бобруйский дуб-богатырь». Дубу более трёхсот лет.\n\n🌿 ОСОБЕННОСТИ:\nДиаметр ствола памятника природы — 1,4 м, высота — 28 м. Крона простирается на 17,1 м с севера на юг и на 24,2 м с востока на запад. В презентации отдельно отмечается парусность кроны как важный для дерева параметр.\n\n🌳 ИСТОРИЧЕСКАЯ ЦЕННОСТЬ:\nДерево находится в городской среде и, согласно материалам презентации, стало свидетелем революций и войн, сохранившись до наших дней.',
'videoUrl':'https://www.youtube.com/watch?v=lID9qVGFLwE','sources':[{'title':'Удодов, А. «Дуб-великан» // Магілёўскія ведамасцi. — 2001. — 6 ноября. — С. 4.'}]},
{
'id':'lukovaya-gora','name':'Ландшафтный заказник «Луковая гора»','category':'landscape','categoryName':'Ландшафтный заказник местного значения','coords':[53.204935,29.230676],'coordsAccuracy':'verified',
'images':['images/luk.jpg','images/luk2.jpg'],'shortDesc':'Участок правого берега Березины на северной окраине Бобруйска между шестым микрорайоном и посёлком Березина. Площадь — 30,5 га.','fullDesc':'📍 МЕСТОНАХОЖДЕНИЕ:\nг. Бобруйск, посёлок Березина; участок правого берега реки Березина на северной окраине города.\n\n📌 СТАТУС И ИСТОРИЯ:\nЛандшафтный заказник местного значения «Луковая гора» образован в 1994 году с целью сохранения характерных форм рельефа Центрально-Березинской водно-ледниковой равнины с богатым растительным и животным миром.\n\n🏞 ОСОБЕННОСТИ:\nПротяжённость заказника — около 1000 м, общая площадь — 30,5 га. Около деревни Луки, старое название посёлка Березина, русло реки почти вплотную подходит к правому склону речной долины. Высота склона над поймой составляет около 30 м.\n\n🌍 ГЕОЛОГИЯ И ЛАНДШАФТ:\nВ формировании местного пейзажа участвовали водно-ледниковые отложения днепровского и сожского оледенений. Здесь также можно наблюдать современную преобразующую деятельность реки. С вершины открывается вид на луг и речную долину.',
'videoUrl':'https://www.youtube.com/watch?v=HPYyQz29i0s','sources':[{'title':'Голубева, Т. «Луковая гора» // Бабруйскае жыццё. — 2009. — 1 июля. — С. 10.'}]},
{
'id':'dubovski-kaskad','name':'Ландшафтный заказник «Дубовский каскад озёр»','category':'landscape','categoryName':'Ландшафтный заказник местного значения','coords':[53.0185,29.3512],'coordsAccuracy':'approximate','images':['images/dubkas.jpg','images/dubkas2.jpg'],'shortDesc':'Уникальный ландшафт долины реки Вирь: на протяжении 14 км река соединяет четыре озера — Драгочин, Усох, Плавун и Вяхово.','fullDesc':'📍 МЕСТОНАХОЖДЕНИЕ:\nБобруйский район, территория Приберезинского лесничества ГЛХУ «Бобруйский лесхоз», в 4 км к западу от агрогородка Телуша. Площадь заказника — 191 га.\n\n📌 СТАТУС И ИСТОРИЯ:\nЛандшафтный заказник местного значения «Дубовский каскад озёр» образован в 1994 году с целью охраны уникальных естественных ландшафтов долины реки Вирь.\n\n💧 КАСКАД ОЗЁР:\nНа протяжении 14 км с севера на юг река Вирь соединяет четыре озера — Драгочин, Усох, Плавун и Вяхово. В презентации отмечено, что такое явление является единственным в Могилёвской области.\n\n🌿 ПРИРОДНАЯ ЦЕННОСТЬ:\nНа территории заказника находятся места обитания и распространения редких видов животных и растений, занесённых в Красную книгу Республики Беларусь и Международную Красную книгу Всемирного союза охраны природы.',
'videoUrl':'https://www.youtube.com/watch?v=GvgooxmePsU','sources':[{'title':'Вербицкий, Е. «Есть чем удивить» // Белорусская лесная газета. — 2014. — 24 апреля. — С. 7.'}],
},
{
'id':'vekovaya-sosna','name':'Ботанический памятник природы «Вековая сосна»','category':'botanical','categoryName':'Ботанический памятник природы местного значения','coords':[53.034,29.14],'coordsAccuracy':'approximate','images':['images/veksos.jpg','images/veksos2.jpg'],'shortDesc':'Великовозрастная сосна в долине Березины, примерно в 4,4 км к юго-востоку от деревни Михайловка. Возраст сосны — 200–250 лет.','fullDesc':'📍 МЕСТОНАХОЖДЕНИЕ:\nБобруйский район, в 4,4 км к юго-востоку от д. Михайловка Горбацевичского сельсовета. Памятник расположен в долине реки Березина, в лесном массиве на правобережье, у южной окраины Центральноберезинской равнины, на границе с Полесской низменностью.\n\n📌 СТАТУС И ИСТОРИЯ:\nБотанический памятник природы местного значения «Вековая сосна» утверждён в 2014 году с целью сохранения местного генофонда. Презентация отмечает его научную, эстетическую и эколого-просветительскую ценность.\n\n🌲 ОСОБЕННОСТИ:\nСосна-гигант произрастает в дубраве площадью 1,5 га. Возраст дуба и сосны в этом великовозрастном насаждении составляет 200–250 лет. Диаметр ствола на высоте 1,3 м — 370 см, общая высота сосны — 35,2 м. Кора отличается от окружающих деревьев и похожа на чешую.\n\n🌳 ОКРУЖЕНИЕ:\nРядом растут ещё одна очень старая сосна с повреждённым у корня стволом и несколько крупных дубов.',
'videoUrl':'','sources':[{'title':'Гладкова, Е. «Древняя сосна получила статус» // Трыбуна працы (Бабруйск). — 2015. — 4 февраля. — С. 4.'}]},
{
'id':'poymennaya-dubrava','name':'Ботанический памятник природы «Пойменная дубрава»','category':'botanical','categoryName':'Ботанический памятник природы местного значения','coords':[53.014,29.253],'coordsAccuracy':'approximate','images':['images/poydubr.jpeg','images/poydubr2.jpeg'],'shortDesc':'Часть лесного массива в пойме Березины площадью 629 га, созданная для сохранения вековых и редких пород деревьев.','fullDesc':'📍 МЕСТОНАХОЖДЕНИЕ:\nБобруйский район, в 10 км к югу от Бобруйска и в 0,6 км к юго-западу от д. Доманово Вишневского сельсовета, в Домановском лесничестве ГЛХУ «Бобруйский лесхоз».\n\n📌 СТАТУС И НАЗНАЧЕНИЕ:\n«Пойменная дубрава» — ботанический памятник природы местного значения, представляющий часть лесного массива в пойме реки Березина. Общая площадь — 629 га. Памятник создан для сохранения отдельных вековых и редких пород деревьев и их групп, ценных в экологическом, научном и эстетическом отношении.\n\n🌳 ДРЕВОСТОЙ:\nЦенные по возрасту и продуктивности участки дубового насаждения занимают более половины площади. Возраст деревьев — 90–100 лет, отдельные дубы достигают 180–200 лет. Основу памятника в равных долях формируют приручейно-пойменная дубрава и черноольшаник таволговый.\n\n🌿 ДРУГИЕ ЛЕСА:\nКроме дубовых насаждений, здесь произрастают черноольховые, сосновые, берёзовые, еловые, грабовые и осиновые леса.',
'videoUrl':'https://www.youtube.com/watch?v=3_5wmaBh_Mc&t=387s','sources':[{'title':'«Пойменная дубрава» // Особо охраняемые природные территории Могилёвской области / под ред. Д. Г. Груммо [и др.]. — Могилёв, 1999. — С. 100.'}]},
]
# Hydrological objects explicitly named in supplied presentation. Only facts actually stated there.
hydro=[
('brody','Броды',1998,10,'ГЛХУ «Бобруйский лесхоз»','Уникальный по природной ценности объект для данной местности.','images/brodi.jpeg','images/brodi2.jpeg'),
('velikie-brody','Великие Броды',1998,52,'ГЛХУ «Бобруйский лесхоз»','Уникальный по природной ценности объект для данной местности.','images/brodi.jpeg','images/brodi2.jpeg'),
('velikoe','Великое',1995,136,'ГЛХУ «Бобруйский лесхоз»','Уникальный по природной ценности объект для данной местности.','images/velikoe.jpg','images/velikoe2.jpg'),
('goreloye','Горелое',1998,72,'ГЛХУ «Бобруйский лесхоз»','Уникальный по природной ценности объект для данной местности.','images/goreloye.png',None),
('lesnoy-moh','Лесной мох',1995,136,'ГЛХУ «Бобруйский лесхоз»','Уникальный по природной ценности объект для данной местности.','images/moh.jpeg',None),
('lipnyaki','Липняки',1994,379,'ГЛХУ «Бобруйский лесхоз»','Уникальный по природной ценности объект для данной местности.','images/lipnyaki.jpg','images/lipnyaki2.jpg'),
('podraga','Подрага',1997,57,'ГЛХУ «Бобруйский лесхоз»','Уникальный по природной ценности объект для данной местности.','images/podvelikiy_moh.jpg','images/podvelikiy_moh2.jpg'),
('tazhilovichski-moh','Тажиловичский мох',2010,240,'СПК «Колхоз им. Невского»','В презентации указано, что охранный режим введён в 2010 году.','images/moh.jpeg',None),
('terehovka','Тереховка',2000,129,'ГЛХУ «Бобруйский лесхоз»','Уникальный по природной ценности объект для данной местности.','images/velikoe.jpg',None),
]
for id_,name,year,area,owner,note,img1,img2 in hydro:
    imgs=[img1]+([img2] if img2 else [])
    desc=f'📍 МЕСТОНАХОЖДЕНИЕ И СТАТУС:\nГидрологический заказник местного значения «{name}».\n\n📌 СВЕДЕНИЯ ИЗ ПРЕЗЕНТАЦИИ:\n{("Статус ООПТ присвоен" if name=="Тереховка" else "Создан") } в {year} году. Площадь — {area} га. '
    if owner: desc += f'Относится к {owner}. '
    desc += note
    if name=='Тажиловичский мох': desc='📍 МЕСТОНАХОЖДЕНИЕ И СТАТУС:\nГидрологический заказник местного значения «Тажиловичский мох».\n\n📌 СВЕДЕНИЯ ИЗ ПРЕЗЕНТАЦИИ:\nОхранный режим введён в 2010 году. Заказник находится на территории СПК «Колхоз им. Невского». Площадь — 240 га.'
    if name=='Тереховка': desc='📍 МЕСТОНАХОЖДЕНИЕ И СТАТУС:\nГидрологический заказник местного значения «Тереховка».\n\n📌 СВЕДЕНИЯ ИЗ ПРЕЗЕНТАЦИИ:\nСтатус ООПТ присвоен в 2000 году. Место нахождения — Бобруйский район, ГЛХУ «Бобруйский лесхоз». Площадь — 129 га. Природная ценность — уникальный по природной ценности объект для данной местности.'
    objects.append({'id':id_,'name':f'Гидрологический заказник «{name}»','category':'hydrological','categoryName':'Гидрологический заказник местного значения','coords':None,'images':imgs,'shortDesc':f'{name}: {area} га, {year} год. '+(f'{owner}.' if owner else ''),'fullDesc':desc,'videoUrl':'','sources':[{'title':'Презентация «Особо охраняемые территории Бобруйщины», слайды 17–25.'}]})

# Existing videos are intentionally preserved only for the four links supplied by the user.
# Remove accidental/unsupported additional objects by writing exactly the 14 named in the source.
assert len(objects)==14, len(objects)

# Generate localized data with faithful translations of the same source-backed facts.
translations={
'ru':{},
'be':{},
'en':{},
'zh':{}
}
# manual translated top five
be_top={
'dub-velikan':('Батанічны помнік прыроды «Бабруйскі дуб-велікан»','Батанічны помнік прыроды мясцовага значэння','Дуб-велікан на скрыжаванні вуліц Гогаля і Чангарскай — старажыл Бабруйска ва ўзросце больш за трыста гадоў.'),
'lukovaya-gora':('Ландшафтны заказнік «Лукавая гара»','Ландшафтны заказнік мясцовага значэння','Участак правага берага Бярэзіны на паўночнай ускраіне Бабруйска паміж шостым мікрараёнам і пасёлкам Беразіна. Плошча — 30,5 га.'),
'dubovski-kaskad':('Ландшафтны заказнік «Дубоўскі каскад азёр»','Ландшафтны заказнік мясцовага значэння','Унікальны ландшафт даліны ракі Вір: на працягу 14 км рака злучае чатыры азёры — Драгочын, Усох, Плавун і Вяхова.'),
'vekovaya-sosna':('Батанічны помнік прыроды «Векавая хвоя»','Батанічны помнік прыроды мясцовага значэння','Векавая хвоя ў даліне Бярэзіны, прыкладна за 4,4 км на паўднёвы ўсход ад вёскі Міхайлаўка. Узрост — 200–250 гадоў.'),
'poymennaya-dubrava':('Батанічны помнік прыроды «Пойменная дубрава»','Батанічны помнік прыроды мясцовага значэння','Частка ляснога масіву ў пойме Бярэзіны плошчай 629 га, створаная для захавання векавых і рэдкіх парод дрэў.')}
en_top={
'dub-velikan':('Botanical Natural Monument “Bobruisk Giant Oak”','Botanical Natural Monument of local significance','The giant oak at the intersection of Gogol and Chongarskaya Streets is a Bobruisk old-timer more than three hundred years old.'),
'lukovaya-gora':('Landscape Reserve “Lukovaya Gora”','Landscape Reserve of local significance','A section of the right bank of the Berezina River on the northern edge of Bobruisk, between the sixth microdistrict and the Berezina settlement. Area — 30.5 ha.'),
'dubovski-kaskad':('Landscape Reserve “Dubovski Cascade of Lakes”','Landscape Reserve of local significance','A unique landscape of the Vir River valley: over 14 km the river connects four lakes — Dragochin, Usokh, Plavun and Vyakhovo.'),
'vekovaya-sosna':('Botanical Natural Monument “Century Pine”','Botanical Natural Monument of local significance','An old-growth pine in the Berezina valley, about 4.4 km southeast of Mikhailovka village. Age — 200–250 years.'),
'poymennaya-dubrava':('Botanical Natural Monument “Floodplain Oak Forest”','Botanical Natural Monument of local significance','Part of a forest massif in the Berezina floodplain covering 629 ha, created to preserve old and rare tree species.')}
zh_top={
'dub-velikan':('植物自然纪念碑“博布鲁伊斯克巨橡”','地方级植物自然纪念碑','位于果戈里街与琼加尔斯卡娅街交叉口的巨橡，是博布鲁伊斯克一棵树龄超过300年的古树。'),
'lukovaya-gora':('景观保护区“卢科瓦亚山”','地方级景观保护区','位于博布鲁伊斯克北部边缘别列津纳河右岸，介于第六微区和别列津纳居民点之间。面积30.5公顷。'),
'dubovski-kaskad':('景观保护区“杜博夫湖泊链”','地方级景观保护区','维尔河谷的独特景观：河流在14公里范围内连接四个湖泊——德拉戈钦、乌索赫、普拉文和维亚霍沃。'),
'vekovaya-sosna':('植物自然纪念碑“世纪松”','地方级植物自然纪念碑','位于别列津纳河谷、米哈伊洛夫卡村东南约4.4公里的一株古松。树龄200–250年。'),
'poymennaya-dubrava':('植物自然纪念碑“河漫滩橡树林”','地方级植物自然纪念碑','别列津纳河漫滩中的一片森林，面积629公顷，用于保护古老和珍稀树种。')}
# Direct, source-faithful full texts for top 5 are translated compactly rather than adding new facts.
for lang in ['ru','be','en','zh']:
    out=[]
    for o in objects:
        x=dict(o)
        if lang=='ru':
            pass
        elif lang in ('be','en','zh') and o['id'] in {'dub-velikan','lukovaya-gora','dubovski-kaskad','vekovaya-sosna','poymennaya-dubrava'}:
            top={'be':be_top,'en':en_top,'zh':zh_top}[lang][o['id']]
            x['name'],x['categoryName'],x['shortDesc']=top
            # Translate full description by keeping factual structure concise.
            if o['id']=='dub-velikan':
                if lang=='be': x['fullDesc']='📍 МЕСЦАХОЖАННЕ:\nг. Бабруйск, скрыжаванне вуліц Гогаля і Чангарскай, каля Бабруйскай крэпасці.\n\n📌 СТАТУС І ГІСТОРЫЯ:\nУ 2003 годзе дрэва абвешчана батанічным помнікам прыроды мясцовага значэння «Бабруйскі дуб-багатыр». Дубу больш за трыста гадоў.\n\n🌿 АСАБЛІВАСЦІ:\nДыяметр ствала — 1,4 м, вышыня — 28 м. Крона распасціраецца на 17,1 м з поўначы на поўдзень і на 24,2 м з усходу на захад. У прэзентацыі асобна адзначана паруснасць кроны.'
                elif lang=='en': x['fullDesc']='📍 LOCATION:\nBobruisk, intersection of Gogol and Chongarskaya Streets, near the Bobruisk Fortress.\n\n📌 STATUS AND HISTORY:\nIn 2003 the tree was declared a botanical natural monument of local significance. It is more than three hundred years old.\n\n🌿 FEATURES:\nTrunk diameter — 1.4 m; height — 28 m. The crown extends 17.1 m north–south and 24.2 m east–west. The presentation separately notes the importance of crown wind load.'
                else: x['fullDesc']='📍 位置：\n白俄罗斯博布鲁伊斯克，果戈里街与琼加尔斯卡娅街交叉口，靠近博布鲁伊斯克要塞。\n\n📌 地位与历史：\n2003年该树被认定为地方级植物自然纪念碑，树龄超过300年。\n\n🌿 特征：\n树干直径1.4米，高28米。树冠南北约17.1米，东西约24.2米。原始演示材料特别指出树冠受风面积的重要性。'
            elif o['id']=='lukovaya-gora':
                if lang=='be': x['fullDesc']='📍 МЕСЦАХОЖАННЕ:\nг. Бабруйск, пасёлак Беразіна; участак правага берага ракі Бярэзіна на паўночнай ускраіне горада.\n\n📌 СТАТУС І ГІСТОРЫЯ:\nЗаказнік утвораны ў 1994 годзе для захавання характэрных формаў рэльефу Цэнтральнабярэзінскай водна-ледавіковай раўніны з багатым раслінным і жывёльным светам.\n\n🏞 АСАБЛІВАСЦІ:\nПрацягласць — каля 1000 м, плошча — 30,5 га. Вышыня схілу над поймай — каля 30 м.\n\n🌍 ГЕАЛОГІЯ:\nУ фарміраванні мясцовага пейзажу ўдзельнічалі водна-ледавіковыя адклады дняпроўскага і сожскага абледзяненняў; можна назіраць і сучасную дзейнасць ракі.'
                elif lang=='en': x['fullDesc']='📍 LOCATION:\nBobruisk, Berezina settlement; a section of the right bank of the Berezina River on the northern edge of the city.\n\n📌 STATUS AND HISTORY:\nThe reserve was established in 1994 to preserve characteristic landforms of the Central Berezina glacial-water plain and its rich flora and fauna.\n\n🏞 FEATURES:\nLength — about 1,000 m; area — 30.5 ha. The slope rises about 30 m above the floodplain.\n\n🌍 GEOLOGY:\nThe local landscape was shaped by glaciofluvial deposits of the Dnieper and Sozh glaciations; modern river activity can also be observed.'
                else: x['fullDesc']='📍 位置：\n博布鲁伊斯克别列津纳居民点，城市北部别列津纳河右岸。\n\n📌 地位与历史：\n保护区建于1994年，用于保护中央别列津纳冰水平原的典型地貌及其丰富的动植物。\n\n🏞 特征：\n长度约1000米，面积30.5公顷，河漫滩以上坡高约30米。\n\n🌍 地质：\n当地景观受到第聂伯河和索日冰期冰水沉积物影响，也能观察到现代河流活动。'
            elif o['id']=='dubovski-kaskad':
                if lang=='be': x['fullDesc']='📍 МЕСЦАХОЖАННЕ:\nБабруйскі раён, Прыбярэзінскае лясніцтва ГЛХУ «Бабруйскі лясгас», у 4 км на захад ад аграгарадка Цялуша. Плошча — 191 га.\n\n📌 СТАТУС І ГІСТОРЫЯ:\nУтвораны ў 1994 годзе для аховы ўнікальных прыродных ландшафтаў даліны ракі Вір.\n\n💧 КАСКАД АЗЁР:\nНа працягу 14 км з поўначы на поўдзень рака Вір злучае чатыры азёры — Драгочын, Усох, Плавун і Вяхова. У прэзентацыі адзначана, што такая з’ява адзіная ў Магілёўскай вобласці.\n\n🌿 ПРЫРОДНАЯ КАШТОЎНАСЦЬ:\nТут ёсць месцы пражывання і распаўсюджвання рэдкіх відаў жывёл і раслін, занесеных у Чырвоную кнігу Рэспублікі Беларусь і Міжнародную Чырвоную кнігу Сусветнага саюза аховы прыроды.'
                elif lang=='en': x['fullDesc']='📍 LOCATION:\nBobruisk District, Priberezinskoye forestry of Bobruisk Forestry Enterprise, 4 km west of Telusha agro-town. Area — 191 ha.\n\n📌 STATUS AND HISTORY:\nEstablished in 1994 to protect unique natural landscapes of the Vir River valley.\n\n💧 CASCADE OF LAKES:\nOver 14 km from north to south, the Vir River connects four lakes — Dragochin, Usokh, Plavun and Vyakhovo. The presentation notes that this phenomenon is unique in Mogilev Region.\n\n🌿 NATURAL VALUE:\nThe reserve contains habitats of rare animal and plant species listed in the Red Book of Belarus and the International Red Book of the World Conservation Union.'
                else: x['fullDesc']='📍 位置：\n白俄罗斯莫吉廖夫州博布鲁伊斯克区，特卢沙镇以西4公里的普里别列津斯科耶林业区。面积191公顷。\n\n📌 地位与历史：\n建于1994年，用于保护维尔河谷独特的自然景观。\n\n💧 湖泊链：\n维尔河自北向南14公里范围内连接四个湖泊——德拉戈钦、乌索赫、普拉文和维亚霍沃。演示材料指出这种现象在莫吉廖夫州独一无二。\n\n🌿 自然价值：\n这里有白俄罗斯红皮书及世界自然保护联盟相关红色名录中珍稀动植物的栖息地。'
            elif o['id']=='vekovaya-sosna':
                if lang=='be': x['fullDesc']='📍 МЕСЦАХОЖАННЕ:\nБабруйскі раён, у 4,4 км на паўднёвы ўсход ад в. Міхайлаўка Горбацэвіцкага сельсавета.\n\n📌 СТАТУС І ГІСТОРЫЯ:\nПомнік зацверджаны ў 2014 годзе для захавання мясцовага генафонду; мае навуковую, эстэтычную і эколага-асветніцкую каштоўнасць.\n\n🌲 АСАБЛІВАСЦІ:\nСасна-гігант расце ў дубраве плошчай 1,5 га. Узрост дуба і хвоі — 200–250 гадоў. Дыяметр ствала на вышыні 1,3 м — 370 см, вышыня — 35,2 м. Кара падобная да лускі.\n\n🌳 АСЯРОДДЗЕ:\nПобач растуць яшчэ адна вельмі старая хвоя і некалькі вялікіх дубоў.'
                elif lang=='en': x['fullDesc']='📍 LOCATION:\nBobruisk District, 4.4 km southeast of Mikhailovka village, Gorbacevichi rural council.\n\n📌 STATUS AND HISTORY:\nThe monument was approved in 2014 to preserve the local gene pool and has scientific, aesthetic and educational value.\n\n🌲 FEATURES:\nThe giant pine grows in a 1.5 ha oak stand. The age of the oak and pine is 200–250 years. Trunk diameter at 1.3 m — 370 cm; total height — 35.2 m. The bark resembles scales.\n\n🌳 SURROUNDINGS:\nAnother very old pine and several large oaks grow nearby.'
                else: x['fullDesc']='📍 位置：\n白俄罗斯博布鲁伊斯克区，戈尔巴采维奇乡米哈伊洛夫卡村东南4.4公里。\n\n📌 地位与历史：\n纪念碑于2014年批准设立，用于保护当地基因资源，具有科学、美学和生态教育价值。\n\n🌲 特征：\n巨松生长在1.5公顷橡树林中。橡树和松树树龄200–250年。树干1.3米高处直径370厘米，总高35.2米，树皮像鳞片。\n\n🌳 周围环境：\n附近还有一株非常古老的松树和几棵大型橡树。'
            elif o['id']=='poymennaya-dubrava':
                if lang=='be': x['fullDesc']='📍 МЕСЦАХОЖАННЕ:\nБабруйскі раён, у 10 км на поўдзень ад Бабруйска і ў 0,6 км на паўднёвы захад ад в. Даманава Вішнёўскага сельсавета, у Даманаўскім лясніцтве ГЛХУ «Бабруйскі лясгас».\n\n📌 СТАТУС І НАЗНАЧЭННЕ:\n«Пойменная дубрава» — батанічны помнік прыроды мясцовага значэння. Плошча — 629 га. Створана для захавання векавых і рэдкіх парод дрэў і іх груп.\n\n🌳 ДРЭВАСТОЙ:\nКаштоўныя па ўзросце і прадукцыйнасці ўчасткі дубовых насаджэнняў займаюць больш за палову плошчы. Узрост дрэў — 90–100 гадоў, асобных дубоў — 180–200 гадоў. Аснову ў роўных долях фарміруюць прырэчкавая пойменная дубрава і чорнаалешнік таволгавы.\n\n🌿 ІНШЫЯ ЛЯСЫ:\nТаксама растуць чорнаалешнікавыя, сасновыя, бярозавыя, яловыя, грабавыя і асінавыя лясы.'
                elif lang=='en': x['fullDesc']='📍 LOCATION:\nBobruisk District, 10 km south of Bobruisk and 0.6 km southwest of Domanovo village, in Domanovo forestry of Bobruisk Forestry Enterprise.\n\n📌 STATUS AND PURPOSE:\n“Floodplain Oak Forest” is a botanical natural monument of local significance. Area — 629 ha. It was created to preserve old and rare tree species and their groups.\n\n🌳 TREE STANDS:\nOak stands valuable for age and productivity occupy more than half of the area. Trees are 90–100 years old; individual oaks reach 180–200 years. The monument is based in equal parts on floodplain oak forest and meadowsweet black alder forest.\n\n🌿 OTHER FORESTS:\nBlack alder, pine, birch, spruce, hornbeam and aspen forests also occur here.'
                else: x['fullDesc']='📍 位置：\n白俄罗斯博布鲁伊斯克区，博布鲁伊斯克以南10公里、达马诺沃村西南0.6公里，位于达马诺沃林业区。\n\n📌 地位与用途：\n“河漫滩橡树林”为地方级植物自然纪念碑，面积629公顷，用于保护古老和珍稀树种及其群落。\n\n🌳 林分：\n按树龄和生产力具有价值的橡树林占面积一半以上。树龄90–100年，个别橡树180–200年。主体由河漫滩橡树林和绣线菊黑桤林各占一半组成。\n\n🌿 其他森林：\n还分布有黑桤、松、桦、云杉、鹅耳枥和白杨林。'
        elif lang=='be':
            # Hydro direct translation from source facts only.
            name=o['name'].replace('Гидрологический заказник','Гідралагічны заказнік').replace('Гидрологический','Гідралагічны')
            x['name']=name;x['categoryName']='Гідралагічны заказнік мясцовага значэння'
            x['shortDesc']=o['shortDesc'].replace('Гидрологический','Гідралагічны').replace('год.','год.')
            x['fullDesc']=o['fullDesc'].replace('МЕСТОНАХОЖДЕНИЕ И СТАТУС','МЕСЦАХОЖАННЕ І СТАТУС').replace('СВЕДЕНИЯ ИЗ ПРЕЗЕНТАЦИИ','ЗВЕСТКІ З ПРЭЗЕНТАЦЫІ').replace('Гидрологический заказник местного значения','Гідралагічны заказнік мясцовага значэння').replace('Создан','Створаны').replace('Статус ООПТ присвоен','Статус ААПТ прысвоены').replace('Площадь','Плошча').replace('Относится к','Адносіцца да').replace('Природная ценность','Прыродная каштоўнасць').replace('Охранный режим введён','Ахоўны рэжым уведзены').replace('на территории','на тэрыторыі').replace('район','раён').replace('местного значения','мясцовага значэння').replace('Уникальный по природной ценности объект для данной местности.','Унікальны па прыроднай каштоўнасці аб’ект для дадзенай мясцовасці.')
        elif lang=='en':
            if o['category']=='hydrological':
                nm=o['name'].replace('Гидрологический заказник','Hydrological Reserve'); x['name']=nm;x['categoryName']='Hydrological Reserve of local significance';x['shortDesc']=o['shortDesc'].replace('год.','year.').replace('га','ha');x['fullDesc']=o['fullDesc'].replace('МЕСТОНАХОЖДЕНИЕ И СТАТУС','LOCATION AND STATUS').replace('СВЕДЕНИЯ ИЗ ПРЕЗЕНТАЦИИ','FACTS FROM THE PRESENTATION').replace('Гидрологический заказник местного значения','Hydrological Reserve of local significance').replace('Создан','Established').replace('Статус ООПТ присвоен','Protected status assigned').replace('Площадь','Area').replace('Относится к','Managed by').replace('Природная ценность','Natural value').replace('Охранный режим введён','Protection regime introduced').replace('Уникальный по природной ценности объект для данной местности.','A site of unique natural value for this locality.')
        elif lang=='zh':
            if o['category']=='hydrological':
                name=o['name'].replace('Гидрологический заказник','水文保护区');x['name']=name;x['categoryName']='地方级水文保护区';x['shortDesc']=o['shortDesc'].replace('год.','年').replace('га','公顷');x['fullDesc']=o['fullDesc'].replace('МЕСТОНАХОЖДЕНИЕ И СТАТУС','位置与地位').replace('СВЕДЕНИЯ ИЗ ПРЕЗЕНТАЦИИ','演示材料中的事实').replace('Гидрологический заказник местного значения','地方级水文保护区').replace('Создан','建立于').replace('Статус ООПТ присвоен','保护地位于').replace('Площадь','面积').replace('Относится к','所属单位').replace('Природная ценность','自然价值').replace('Охранный режим введён','保护制度于').replace('Уникальный по природной ценности объект для данной местности.','该地独特的自然价值区域。')
        out.append(x)
    translations[lang]=out
for lang,data in translations.items():
    with open(f'{root}/locales/{lang}-data.json','w',encoding='utf-8') as f: json.dump(data,f,ensure_ascii=False,indent=2)
print('wrote', [len(v) for v in translations.values()])
